app = "artsy-fartsy"
primary_region = "yyz"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.domains]]
  domain = "artsy.rashik.sh"
  type = "primary"

[env]
  PORT = "8000"

[[statics]]
  guest_path = "/app/frontend/dist"
  url_prefix = "/"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
