[phases.setup]
nixPkgs = ['bun']
NIXPACKS_LIBS=openssl

[phases.install]
cmds = ['bun install']

[phases.build]
cmds = ['bunx prisma generate', 
        'bunx prisma migrate deploy']

[start]
cmd = 'bun run index.ts'